name: Metrics
on:
  schedule: [{ cron: "0 */8 * * *" }]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: fuji-184
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          plugin_followup_sections: repositories, user
          plugin_lines: yes
          plugin_stargazers: yes
